# Generated by Django 3.2.4 on 2021-10-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
