# Generated by Django 3.2.4 on 2021-10-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_site', '0002_participant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
