# Generated by Django 3.2.4 on 2021-10-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_site', '0003_alter_participant_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciprocity', models.BooleanField(default=False)),
                ('id_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_to', to='meeting_site.participant')),
                ('id_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_from', to='meeting_site.participant')),
            ],
            options={
                'verbose_name': 'Взаимность',
                'verbose_name_plural': 'Взаимности',
            },
        ),
    ]
