# Generated by Django 3.2.4 on 2021-10-19 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_site', '0004_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_from', to='meeting_site.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='id_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_to', to='meeting_site.participant'),
        ),
    ]
